name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        git clone https://github.com/daniel-kelley/libriffr
        make -C libriffr
        sudo make -C libriffr install
        sudo ldconfig -v
    - name: make
      run: make
