name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: |
        sudo apt-get install csound
        sudo apt-get install csound-utils
        sudo apt-get install clang-tools
        git clone https://github.com/daniel-kelley/libriffr
        make -C libriffr
        sudo make -C libriffr install
        sudo ldconfig -v
    - name: make
      run: make
    - name: make check
      run: |
        make clean
        make libs
        make SANITIZE=address check
    - name: make install
      run: |
        make clean
        sudo make install
    - name: install check
      run: |
        which test
        /usr/bin/test -f /usr/local/bin/pvocf-info
        /usr/bin/test -f /usr/local/include/pvocf.h
        /usr/bin/test -f /usr/local/lib/libpvocf.a
        /usr/bin/test -f /usr/local/lib/libpvocf-0.1.so
        /usr/bin/test -L /usr/local/lib/libpvocf.so
    - name: make uninstall
      run: |
        sudo make uninstall
    - name: uninstall check
      run: |
        test \! -f /usr/local/bin/pvocf-info
        test \! -f /usr/local/include/pvocf.h
        test \! -f /usr/local/lib/libpvocf.a
        test \! -f /usr/local/lib/libpvocf-0.1.so
        test \! -L /usr/local/lib/libpvocf.so
    - name: make check clang
      run: |
        make clean
        make CC=clang libs
        make CC=clang SANITIZE=address check
    - name: scan-build make
      run: |
        make clean
        scan-build make
